---
tools_namespace: va3azs-patricksimonian-ocp201-tst-tools
dev_namespace: va3azs-patricksimonian-ocp201-tst-dev
github_repo: strapi-demo
github_owner: patricksimonian
strapi_infra_name: strapi
mongo_infra_name: mongo-ha
mongo_backup_infra_name: mongo-ha-backup
prod_image_tag: prod 
test_image_tag: test
