---
  - hosts: localhost
    gather_facts: no
    connection: local
    vars_files:
     - vars.yml
    vars:
      version: "{{ lookup('template', './templates/pr_tag.j2') }}"
      namespace: "{{ dev_namespace }}"
      suffix: "{{ version }}"
      image_namespace: "{{ tools_namespace }}"
      infra_name: "{{ mongo_infra_name }}"
      # mongo operation settings
      first_mongo_pod: "{{ mongo_infra_name }}-0"
    tasks:
  
      # - name: Verify environment setup and prerequisites
      #   include_tasks: tasks/env-verify.yml
  
      # - name: Clear start before deployment
      #   include_tasks: tasks/clear_object.yml
      #   vars:
      #     LABEL: "{{ APP_LABEL }}"

      - name: deploy {{ infra_name }} of PR {{ PR }} in {{ namespace }} namespace
        shell: >
          oc process -n "{{ namespace }}" -f "../templates/mongo/stateful-set.yaml" {{ deploy_params }} | 
          oc apply -n "{{ namespace }}" -f -
        vars:
          deploy_params: "{{ lookup('template', './templates/deploy_mongo.param.j2') }}"
      # - name: Deploy MongoDB statefulset
      #   include_tasks: tasks/create_object.yml
      #   vars:
      #     name: "{{ MONGODB_SERVICE_NAME }}"
      #     kind: StatefulSet
      #     template: templates/mongodb-manifest.yml
      #     namespace: "{{ NAMESPACE }}"
      #     ready_status: "{{ MONGODB_REPLICAS }}"
  
      # Check for MongoDB syncing status
  #     - name: Add hosts for MongoDB pods
  #       add_host:
  #         name: "{{ ORIGINAL_SS_POD }}"
  #         groups:
  #         - mongo_pod
      
  #     - debug: msg="------------- Switching to kubectl for pod interaction -------------"
  
  # # Switch to mongo_pod host for pod interaction
  # - hosts: mongo_pod
  #   gather_facts: yes
  #   connection: kubectl
  #   tasks:
  #     - name: Connect to MongoDB pod and verify ReplicaSet is synced up
  #       include_tasks: tasks/replica_set_operation.yml
  
  #     - debug: msg="------- MongoDB ready, continue with App deployment -------"
  